import type { GlobalStyles, ElementStyles, ThemePreset } from '@/types/style';

const defaultGlobalStyles: GlobalStyles = {
  fontSize: 16,
  fontFamily: 'system-ui, -apple-system, sans-serif',
  textColor: '#1a1a1a',
  backgroundColor: '#ffffff',
  lineHeight: 1.6,
  linkColor: '#0066cc',
  codeBackground: '#f5f5f5',
  maxWidth: 800,
  padding: { top: 40, right: 40, bottom: 40, left: 40 },
};

export const themePresets: Record<ThemePreset, GlobalStyles> = {
  default: defaultGlobalStyles,
  dark: {
    fontSize: 16,
    fontFamily: 'system-ui, -apple-system, sans-serif',
    textColor: '#e0e0e0',
    backgroundColor: '#1a1a1a',
    lineHeight: 1.6,
    linkColor: '#6db3f2',
    codeBackground: '#2d2d2d',
    maxWidth: 800,
    padding: { top: 40, right: 40, bottom: 40, left: 40 },
  },
  document: {
    fontSize: 14,
    fontFamily: 'Georgia, "Times New Roman", serif',
    textColor: '#333333',
    backgroundColor: '#ffffff',
    lineHeight: 1.8,
    linkColor: '#1a0dab',
    codeBackground: '#f8f8f8',
    maxWidth: 700,
    padding: { top: 60, right: 60, bottom: 60, left: 60 },
  },
  blog: {
    fontSize: 18,
    fontFamily: '"Noto Sans KR", system-ui, sans-serif',
    textColor: '#2c2c2c',
    backgroundColor: '#fafafa',
    lineHeight: 2.0,
    linkColor: '#0070f3',
    codeBackground: '#f0f0f0',
    maxWidth: 720,
    padding: { top: 48, right: 24, bottom: 48, left: 24 },
  },
  minimal: {
    fontSize: 14,
    fontFamily: 'system-ui, -apple-system, sans-serif',
    textColor: '#000000',
    backgroundColor: '#ffffff',
    lineHeight: 1.5,
    linkColor: '#000000',
    codeBackground: '#f5f5f5',
    maxWidth: 650,
    padding: { top: 20, right: 20, bottom: 20, left: 20 },
  },
  sepia: {
    fontSize: 16,
    fontFamily: 'Georgia, "Times New Roman", serif',
    textColor: '#5b4636',
    backgroundColor: '#f4ecd8',
    lineHeight: 1.7,
    linkColor: '#8b4513',
    codeBackground: '#ede3cb',
    maxWidth: 750,
    padding: { top: 48, right: 48, bottom: 48, left: 48 },
  },
  ocean: {
    fontSize: 16,
    fontFamily: 'system-ui, -apple-system, sans-serif',
    textColor: '#e0f0ff',
    backgroundColor: '#0d1b2a',
    lineHeight: 1.6,
    linkColor: '#48cae4',
    codeBackground: '#1b2838',
    maxWidth: 800,
    padding: { top: 40, right: 40, bottom: 40, left: 40 },
  },
  forest: {
    fontSize: 16,
    fontFamily: 'system-ui, -apple-system, sans-serif',
    textColor: '#2d3b2d',
    backgroundColor: '#f0f5ed',
    lineHeight: 1.7,
    linkColor: '#2e7d32',
    codeBackground: '#e2ebe0',
    maxWidth: 780,
    padding: { top: 44, right: 44, bottom: 44, left: 44 },
  },
  sunset: {
    fontSize: 16,
    fontFamily: 'system-ui, -apple-system, sans-serif',
    textColor: '#f5e6d3',
    backgroundColor: '#2d1b2e',
    lineHeight: 1.6,
    linkColor: '#ff9a56',
    codeBackground: '#3a2240',
    maxWidth: 800,
    padding: { top: 40, right: 40, bottom: 40, left: 40 },
  },
  newspaper: {
    fontSize: 15,
    fontFamily: '"Times New Roman", Times, serif',
    textColor: '#1a1a1a',
    backgroundColor: '#f5f2ea',
    lineHeight: 1.5,
    linkColor: '#333333',
    codeBackground: '#e8e5dd',
    maxWidth: 700,
    padding: { top: 36, right: 36, bottom: 36, left: 36 },
  },
  academic: {
    fontSize: 14,
    fontFamily: '"Computer Modern", Georgia, serif',
    textColor: '#222222',
    backgroundColor: '#ffffff',
    lineHeight: 1.8,
    linkColor: '#004080',
    codeBackground: '#f0f0f0',
    maxWidth: 680,
    padding: { top: 64, right: 64, bottom: 64, left: 64 },
  },
  notebook: {
    fontSize: 16,
    fontFamily: '"Segoe UI", system-ui, sans-serif',
    textColor: '#333333',
    backgroundColor: '#fffef5',
    lineHeight: 1.9,
    linkColor: '#4a7cbb',
    codeBackground: '#f5f4eb',
    maxWidth: 740,
    padding: { top: 40, right: 48, bottom: 40, left: 48 },
  },
  terminal: {
    fontSize: 14,
    fontFamily: '"Fira Code", "JetBrains Mono", "Cascadia Code", monospace',
    textColor: '#00ff00',
    backgroundColor: '#0a0a0a',
    lineHeight: 1.5,
    linkColor: '#00ccff',
    codeBackground: '#1a1a1a',
    maxWidth: 850,
    padding: { top: 32, right: 32, bottom: 32, left: 32 },
  },
  elegant: {
    fontSize: 17,
    fontFamily: '"Playfair Display", Georgia, serif',
    textColor: '#2c2c2c',
    backgroundColor: '#faf8f5',
    lineHeight: 1.8,
    linkColor: '#8b6914',
    codeBackground: '#f0ede6',
    maxWidth: 720,
    padding: { top: 56, right: 56, bottom: 56, left: 56 },
  },
  pastel: {
    fontSize: 16,
    fontFamily: '"Nunito", system-ui, sans-serif',
    textColor: '#4a4a6a',
    backgroundColor: '#fdf2f8',
    lineHeight: 1.7,
    linkColor: '#c084fc',
    codeBackground: '#f3e8ff',
    maxWidth: 760,
    padding: { top: 44, right: 44, bottom: 44, left: 44 },
  },
};

export const themeElementStyles: Partial<Record<ThemePreset, ElementStyles>> = {
  default: {
    h1: { borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.15)' },
    h2: { borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.15)' },
    hr: { backgroundColor: 'rgba(0,0,0,0.15)' },
    code: { borderRadius: 6 },
  },
  dark: {
    h1: { color: '#ffffff', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.15)' },
    h2: { color: '#ffffff', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.15)' },
    strong: { color: '#ffffff' },
    hr: { backgroundColor: 'rgba(255,255,255,0.15)' },
    code: { borderRadius: 6 },
  },
  document: {
    h1: { color: '#1a1a1a', borderBottomStyle: 'solid', borderBottomWidth: 2, borderBottomColor: '#333333' },
    h2: { color: '#1a1a1a', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: '#cccccc' },
    strong: { color: '#111111' },
    hr: { backgroundColor: '#cccccc' },
    code: { borderRadius: 4, borderStyle: 'solid', borderWidth: 1, borderColor: '#e0e0e0' },
  },
  blog: {
    h1: { color: '#111111', borderBottomStyle: 'none' },
    h2: { color: '#0070f3', borderBottomStyle: 'solid', borderBottomWidth: 2, borderBottomColor: '#0070f3' },
    strong: { color: '#0070f3' },
    hr: { backgroundColor: '#e0e0e0' },
    code: { borderRadius: 8 },
  },
  minimal: {
    h1: { borderBottomStyle: 'none' },
    h2: { borderBottomStyle: 'none' },
    hr: { backgroundColor: '#e0e0e0' },
    code: { borderRadius: 0 },
  },
  sepia: {
    h1: { color: '#3e2c1a', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: '#c4a882' },
    h2: { color: '#4a3422', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: '#d4c4a8' },
    strong: { color: '#6b3a2a' },
    hr: { backgroundColor: '#c4a882' },
    code: { borderRadius: 4, borderStyle: 'solid', borderWidth: 1, borderColor: '#c4a882' },
  },
  ocean: {
    h1: { color: '#90e0ef', borderBottomStyle: 'solid', borderBottomWidth: 2, borderBottomColor: '#48cae4' },
    h2: { color: '#90e0ef', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: 'rgba(72,202,228,0.4)' },
    strong: { color: '#48cae4' },
    hr: { backgroundColor: 'rgba(72,202,228,0.3)' },
    code: { borderRadius: 6, borderStyle: 'solid', borderWidth: 1, borderColor: '#1b3a4b' },
  },
  forest: {
    h1: { color: '#1b5e20', borderBottomStyle: 'solid', borderBottomWidth: 2, borderBottomColor: '#2e7d32' },
    h2: { color: '#2e7d32', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: '#a5d6a7' },
    strong: { color: '#388e3c' },
    hr: { backgroundColor: '#a5d6a7' },
    code: { borderRadius: 4, borderStyle: 'solid', borderWidth: 1, borderColor: '#c8e6c9' },
  },
  sunset: {
    h1: { color: '#ffcba4', borderBottomStyle: 'solid', borderBottomWidth: 2, borderBottomColor: '#ff9a56' },
    h2: { color: '#ffcba4', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: 'rgba(255,154,86,0.4)' },
    strong: { color: '#ff9a56' },
    hr: { backgroundColor: 'rgba(255,154,86,0.3)' },
    code: { borderRadius: 6, borderStyle: 'solid', borderWidth: 1, borderColor: '#4a2850' },
  },
  newspaper: {
    h1: { color: '#000000', borderBottomStyle: 'double', borderBottomWidth: 3, borderBottomColor: '#1a1a1a' },
    h2: { borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: '#999999' },
    hr: { backgroundColor: '#1a1a1a' },
    code: { borderRadius: 0, borderStyle: 'solid', borderWidth: 1, borderColor: '#cccccc' },
  },
  academic: {
    h1: { color: '#1a1a1a', borderBottomStyle: 'solid', borderBottomWidth: 2, borderBottomColor: '#222222' },
    h2: { color: '#333333', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: '#999999' },
    strong: { color: '#004080' },
    hr: { backgroundColor: '#999999' },
    code: { borderRadius: 2, borderStyle: 'solid', borderWidth: 1, borderColor: '#d0d0d0' },
  },
  notebook: {
    h1: { color: '#4a7cbb', borderBottomStyle: 'dashed', borderBottomWidth: 1, borderBottomColor: '#b0b0a0' },
    h2: { color: '#4a7cbb', borderBottomStyle: 'dashed', borderBottomWidth: 1, borderBottomColor: '#c8c8b8' },
    strong: { color: '#2a5a8a' },
    hr: { backgroundColor: '#c8c8b8' },
    code: { borderRadius: 4 },
  },
  terminal: {
    h1: { color: '#39ff14', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: '#00ff00' },
    h2: { color: '#00cc00', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: '#005500' },
    strong: { color: '#ffff00' },
    hr: { backgroundColor: '#005500' },
    code: { borderRadius: 0, borderStyle: 'solid', borderWidth: 1, borderColor: '#333333' },
  },
  elegant: {
    h1: { color: '#8b6914', borderBottomStyle: 'solid', borderBottomWidth: 1, borderBottomColor: '#8b6914' },
    h2: { color: '#6b5010', borderBottomStyle: 'none' },
    strong: { color: '#8b6914' },
    hr: { backgroundColor: '#ddd5c4' },
    code: { borderRadius: 4, borderStyle: 'solid', borderWidth: 1, borderColor: '#ddd5c4' },
  },
  pastel: {
    h1: { color: '#7c3aed', borderBottomStyle: 'solid', borderBottomWidth: 2, borderBottomColor: '#c084fc' },
    h2: { color: '#9333ea', borderBottomStyle: 'none' },
    strong: { color: '#ec4899' },
    hr: { backgroundColor: '#e8d5f5' },
    code: { borderRadius: 8 },
  },
};

export const defaultStyles = defaultGlobalStyles;
export const presetKeys: ThemePreset[] = [
  'default', 'dark', 'document', 'blog', 'minimal',
  'sepia', 'ocean', 'forest', 'sunset', 'newspaper',
  'academic', 'notebook', 'terminal', 'elegant', 'pastel',
];
